version : '2.2'
networks:
  nginx-net:
    external: true
services:
  www.nginx.com:
        container_name : nginx
        hostname: nginx

        restart: on-failure

        networks:
          nginx-net:
            ipv4_address: 172.28.159.254
        image: registry.cn-hangzhou.aliyuncs.com/yangyuanpeng/nginx:1.15.6
        volumes:
          - ./conf.d:/etc/nginx/conf.d   #nginx子配置文件
          - ./log:/var/log/nginx  #nginx日志目录
          - /data/download:/data/download
          - /etc/localtime:/etc/localtime:ro
        ports :
          - 83:80

